apiVersion: batch/v1
kind: CronJob
metadata:
  name: double-request-cronjob
spec:
  schedule: "*/1 * * * *"  # ✅ Alle 5 Minuten
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: double-request
        spec:
          restartPolicy: Never  # ✅ Pod soll nach der Ausführung beendet werden
          containers:
            - name: 2gays1straight-client
              image: ghcr.io/maytastico/2gays1straight-client
              args: ["--flag","FromTwoPodsTwice", "--id", "gay_potato","--server","http://ctf-server.ctf-server:8080"]
            volumeMounts:
              - name: ctf-config
                mountPath: /etc/ctf
            env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          volumes:
            - name: ctf-config
              configMap:
                name: ctf-configmap
