apiVersion: batch/v1
kind: Job
metadata:
  name: one-time-request
spec:
  parallelism: 2
  completions: 2
  template:
    metadata:
      labels:
        app: one-time-request
    spec:
      restartPolicy: Never  # ✅ Pod wird nicht neugestartet
      containers:
       - name: 2gays1straight-client
         image: ghcr.io/maytastico/2gays1straight-client
         args: ["--flag","FromTwoPodsOnce", "--id", "gay_potato","--server","http://ctf-server.ctf-server:8080"]
         volumeMounts:
           - name: ctf-config
             mountPath: /etc/ctf
         env:
         - name: POD_NAME
           valueFrom:
             fieldRef:
               fieldPath: metadata.name
         - name: POD_NAMESPACE
           valueFrom:
             fieldRef:
               fieldPath: metadata.namespace
      volumes:
         - name: ctf-config
           configMap:
             name: ctf-configmap

