apiVersion: v1
kind: Pod
metadata:
  name: 2gays1straight
  labels:
    app: best-app
  namespace: 2gays1straight 
spec:
  containers:
  - name: 2gays1straight-client
    image: ghcr.io/maytastico/2gays1straight-client
    args: ["--flag","ConfigMap","--server","http://ctf-server.ctf-server:8080"]
    volumeMounts:
      - name: config-volume
        mountPath: /etc/ctf/config/
    env:
    - name: POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: POD_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
  volumes:
    - name: config-volume
      configMap:
        name: gayest-config
          
