apiVersion: v1
kind: Pod
metadata:
  name: 2gays1straight
  labels:
    app: best-app
  namespace: 2gays1straight 
spec:
  serviceAccountName: straightmin
  containers:
  - name: 2gays1straight-client
    image: ghcr.io/maytastico/2gays1straight-client
    args: ["--flag","SecurityConext","--server","http://ctf-server.ctf-server:8080"]
    volumeMounts:
      - name: ctf-config
        mountPath: /etc/ctf
    env:
    - name: POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: POD_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
  volumes:
    - name: ctf-config
      configMap:
        name: ctf-configmap
