apiVersion: v1
kind: ServiceAccount
metadata:
  name: straightmin
  namespace: 2gays1straight

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: straightmin-role
  namespace: 2gays1straight
rules:
  - apiGroups: [""]
    resources: ["pods"]
    resourceNames: ["2gays1straight"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["configmaps"]
    resourceNames: ["ctf-configmap"]
    verbs: ["get", "list"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: straightmin-rolebinding
  namespace: 2gays1straight
subjects:
  - kind: ServiceAccount
    name: straightmin
    namespace: 2gays1straight
roleRef:
  kind: Role
  name: straightmin-role
  apiGroup: rbac.authorization.k8s.io